[package]
name = "endptr"
version = "0.1.0"
edition = "2024"
description = "HTTP TUI"
categories = ["command-line-interface", "development-tools"]
authors = ["Wilovy09"]
license = "MIT"
repository = "https://github.com/Wilovy09/endptr"
homepage = "https://github.com/Wilovy09/endptr"

[[bin]]
name = "endptr"
path = "src/main.rs"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.30.0", features = ["all-widgets", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
srtemplate = "0.3.3"
reqwest = { version = "0.12", features = ["blocking"] }
arboard = "3"
