[package]
name = "endptr"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "endptr"
path = "src/main.rs"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.30.0", features = ["all-widgets", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
srtemplate = "0.3.3"
reqwest = { version = "0.12", features = ["blocking"] }
arboard = "3"
