[package]
name = "endptr"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "endptr"
path = "src/main.rs"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
